swagger: "2.0"
info:
  version: "0.0.1"
  title: Swagger API
# during dev, should point to your local machine
# host: 0.0.0.0:8080
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:

  /general/getAccounts:
    # binds a127 app logic to a route
    x-swagger-router-controller: info
    get:
      tags:
        - general
      description: ""
      # used as the method name of the controller
      operationId: getAccounts              
      responses:
        '200':
          description: ""
          schema:
            type: array
            items:
              type: string
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
          
  /humanworkerfactory/createHumanWorker:
    # binds a127 app logic to a route
    x-swagger-router-controller: info
    post:
      tags:
        - humanworkerfactory
      description: ""
      # used as the method name of the controller
      operationId: createHumanWorker
      parameters:
        - name: "para"
          in: "body"
          schema:
            properties:
              description:
                type: string
              fromAddress:
                type: string  
              identity:
                type: string 
      responses:
        '200':
          description: ""
          schema:
            properties:
              workToken:
                type: string
              from:
                type: string
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"     

  /humanworkerfactory/getContracts:
    # binds a127 app logic to a route
    x-swagger-router-controller: info
    get:
      tags:
        - humanworkerfactory
      description: ""
      # used as the method name of the controller
      operationId: getContracts
      responses:
        '200':
          description: ""
          schema:
            type: array
            items:
              properties:                           
                tokenAddress:
                  type: string
                tokenName:
                  type: string
                description:
                  type: string
                ownerName:
                  type: string
                ownerAddress:
                  type: string                                                
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"  

  /humanworkertoken/transfer:
    post:
      tags: 
        - humanworkertoken 
      description: "Überträgt Anteile vom ESToken auf anderen Teilnehmer"
      operationId: "transfer"
      parameters:
        - name: "para"
          in: "body"
          schema:
            properties:
              from:
                type: string
              to:
                type: string
              volume:
                type: number
      responses:  
        "200":
          description: Success
          schema: 
            properties:          
              from:
                type: string
              to:
                type: string
              value:
                type: number                
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    x-swagger-router-controller: "info" 

  /humanworkertoken/getTransfers:
    # binds a127 app logic to a route
    x-swagger-router-controller: info
    get:
      tags:
        - humanworkertoken
      description: ""
      # used as the method name of the controller
      operationId: getTransfers
      responses:
        '200':
          description: ""
          schema:
            type: array
            items:
              properties:                           
                to:
                  type: string
                from:
                  type: string
                value:
                  type: number                                                   
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"  

  /humanworkertoken/getContractsByOwner:
    # binds a127 app logic to a route
    x-swagger-router-controller: info
    get:
      tags:
        - humanworkerfactory
      description: ""
      # used as the method name of the controller
      operationId: getContractsByOwner
      parameters:
        - name: "address"
          in: "query"
          type: string
      responses:
        '200':
          description: ""
          schema:
            type: array
            items:
              properties:                           
                tokenAddress:
                  type: string
                tokenName:
                  type: string
                description:
                  type: string
                ownerName:
                  type: string
                ownerAddress:
                  type: string                                                   
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"  

  /humanworkertoken/getContractByAddress:
    # binds a127 app logic to a route
    x-swagger-router-controller: info
    get:
      tags:
        - humanworkerfactory
      description: ""
      # used as the method name of the controller
      operationId: getContractByAddress
      parameters:
        - name: "address"
          in: "query"
          type: string
      responses:
        '200':
          description: ""
          schema:
            type: array
            items:
              properties:                           
                tokenAddress:
                  type: string
                tokenName:
                  type: string
                description:
                  type: string
                ownerName:
                  type: string
                ownerAddress:
                  type: string                                                   
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"  




# complex objects have schema definitions
definitions:
  ErrorResponse:
    type: object    
    properties:
      message:
        type: string

